            - nombre: Cargar un artefacto de compilación
  Usos: actions/upload-artifact@v3.2.2
  con:
    # Nombre del artefacto
    nombre: # opcional, por defecto es artefacto
    # Un archivo, directorio o patrón comodín que describe qué subir
    camino:
    # El comportamiento deseado si no se encuentran archivos utilizando la ruta proporcionada.
Opciones disponibles:
  advertir: Mostrar una advertencia pero no hacer que falle la acción.
  error: La acción falla con un mensaje de error
  ignorar: No se mostrarán advertencias ni errores, la acción no falla.

    if-no-files-found: # opcional, el valor predeterminado es advertir
    # Duración tras la cual el artefacto caducará en días. 0 significa usar la retención predeterminada.
Mínimo 1 día. Máximo 90 días, a menos que se modifique en la página de configuración del repositorio.

    días de retención: # opcional
    # Si es verdadero, los archivos ocultos se incluirán en el artefacto cargado. Si es falso, los archivos ocultos se excluirán del artefacto cargado.

    include-hidden-files: # opcional, el valor predeterminado es falso
          
